100%|██████████| 11/11 [00:00<00:00, 35.16it/s]
100%|██████████| 11/11 [00:00<00:00, 36.27it/s]
[2024-01-31 19:55:40,162][root][INFO] - using 1 gpus
the PU data is ['KA04', 'KA15', 'KA16', 'KA22', 'KA30', 'KB23', 'KB24', 'KB27', 'KI14', 'KI17', 'KI21']
the PU data is ['KA04', 'KA15', 'KA16', 'KA22', 'KA30', 'KB23', 'KB24', 'KB27', 'KI14', 'KI17', 'KI21']
--------PU Dataset:(0, 2) TL Task---------
the TTA infor is {'optim_steps': 2, 'model_episodic': False, 'filter_K': 50, 'temp': 1, 'alpha': 2, 'contrastive_': 1, 'neighbor_K': 5, 'NA_': 1, 'NA_kind': 4, 'version': 'v2', 'B_kind': 1}
the input kind is fft,the model kind is ResNet18
the opt infor is {'name': 'adamw', 'lr_src': 0.001, 'lr_tar': 0.01, 'lr_scheduler': 'fix', 'weight_decay_src': 0.0001, 'weight_decay_tar': 0.001}
the data infor is {'data_name': 'PU', 'data_path': 'D:/P_new/PU_dataset', 'TL_list': [0, 1, 2], 'input_kind': 'fft', 'norm_kind': 'mean-std', 'TL_Task': [0, 2]}
[2024-01-31 19:55:42,298][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [0, 2]: Beginning Acc T = 78.48%;
Model Size：5.628MB
the ResNet8: modelsize 5.628MB flops 34578681.0 and params 1475416.0
Task: [0, 2], Epoch:1/1; Acc_tar/uncertain/certain = 92.33%/89.59%/98.78%;